### ISSUE TITLE
Class .bottom-of-page not allowing for full height of footer buttons on smaller sizes

### ISSUE THREAD

**Issue by afineedge** [EmmaGX/Project-2-Mobile-first-Responsive-Layout#1]
https://github.com/EmmaGX/Project-2-Mobile-first-Responsive-Layout/blob/8bd5dfd3a104c86214ca510974bb315560cb54e1/css/styles.css#L294

**Comment by afineedge** [comment]
This declaration should probably be removed, as it is not allowing for the buttons inside of it (.,bottom-nav-li) to reach their full height without fighting it.

**Comment by afineedge** [comment]
Alternately, this could be changed to `min-height` of 36px or so, meaning it would not constrain the buttons, but would also allow for extra space below the text at smaller sizes.

**Comment by EmmaGX** [comment]
removed bottom-of-page
