### ISSUE TITLE
visibility: hidden should be replaced with display: none

### ISSUE THREAD

**Issue by afineedge** [EmmaGX/Project-2-Mobile-first-Responsive-Layout#3]
https://github.com/EmmaGX/Project-2-Mobile-first-Responsive-Layout/blob/8bd5dfd3a104c86214ca510974bb315560cb54e1/css/styles.css#L166

In all instances of `visibility: hidden`, `display: none` will be a more robust replacement. The visibility attribute only controls whether the element should be visible, but still places it there and has it take up space. `display: none` entirely stops the element from existing on the page. As one example, at small sizes, your footer is taller than it looks like it should be because the invisible <ul> tag is still being placed there, and is wrapping to make itself four buttons tall, even though you can't see it.

**Comment by EmmaGX** [comment]
Changed to display: none;
